version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "Building Spring Boot application..."
      - cd complete
      - chmod +x mvnw
      - ./mvnw clean package

      - echo "Building Docker image..."
      - docker build -t $ECR_URI:latest .

      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_URI:latest

  post_build:
    commands:
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"springboot-container","imageUri":"%s"}]' $ECR_URI:latest > imagedefinitions.json

artifacts:
  files:
    - complete/imagedefinitions.json
